import style from "./BgLanding.module.css";
import {
	SiXbox,
	SiPlaystation,
	SiPlaystation2,
	SiPlaystation3,
	SiPlaystation4,
	SiPlaystationvita,
	SiNintendogamecube,
	SiNintendoswitch,
	SiNintendo3Ds,
	SiWindows,
	SiEpicgames,
} from "react-icons/si";
import { MdOutlineVideogameAsset, MdOutlineGamepad } from "react-icons/md";
import { RiXboxLine, RiGameLine } from "react-icons/ri";
import { GiBulletBill, GiCrosshair, GiPortal } from "react-icons/gi";

function BgLanding() {
	return (
		<section className={style.container}>
			<div className={style.icons}>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
			</div>
			<div className={style.icons}>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
			</div>
			<div className={style.icons}>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
			</div>
			<div className={style.icons}>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
			</div>
			<div className={style.icons}>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
			</div>
			<div className={style.icons}>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
			</div>
			<div className={style.icons}>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
			</div>
			<div className={style.icons}>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
			</div>
			<div className={style.icons}>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
			</div>
			<div className={style.icons}>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
			</div>
			<div className={style.icons}>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
			</div>
			<div className={style.icons}>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
			</div>
			<div className={style.icons}>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
			</div>
			<div className={style.icons}>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
			</div>
			<div className={style.icons}>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
			</div>
			<div className={style.icons}>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
			</div>
			<div className={style.icons}>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
			</div>
			<div className={style.icons}>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
			</div>
			<div className={style.icons}>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
			</div>
			<div className={style.icons}>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
				<div>
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
					<GiBulletBill />
					<SiPlaystation />
					<SiWindows />
					<GiPortal />
					<SiPlaystation3 />
					<SiXbox />
					<MdOutlineVideogameAsset />
					<SiPlaystation2 />
					<RiGameLine />
					<SiNintendo3Ds />
					<MdOutlineGamepad />
					<SiPlaystation4 />
					<SiEpicgames />
					<SiNintendoswitch />
					<GiCrosshair />
					<RiXboxLine />
					<SiPlaystationvita />
					<SiNintendogamecube />
				</div>
			</div>
		</section>
	);
}

export default BgLanding;
